default: &default
  adapter: mysql2

  host: db
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: surfdome_development

test:
  <<: *default
  database: surfdome_test